[2020-10-12 16:16:31,797] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2020-10-12T10:46:25.653007+00:00 [queued]>
[2020-10-12 16:16:31,853] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2020-10-12T10:46:25.653007+00:00 [queued]>
[2020-10-12 16:16:31,853] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-10-12 16:16:31,853] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-10-12 16:16:31,854] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-10-12 16:16:31,968] {taskinstance.py:900} INFO - Executing <Task(GoogleCloudStorageToBigQueryOperator): load_data> on 2020-10-12T10:46:25.653007+00:00
[2020-10-12 16:16:31,973] {standard_task_runner.py:53} INFO - Started process 186309 to run task
[2020-10-12 16:16:32,154] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.load_data 2020-10-12T10:46:25.653007+00:00 [running]> ludicxx
[2020-10-12 16:16:34,231] {taskinstance.py:1145} ERROR - <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/vg-airflow-tutorial-dev/jobs?alt=json returned "Not found: Project vg-airflow-tutorial-dev">
Traceback (most recent call last):
  File "/home/ludicxx/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ludicxx/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/contrib/operators/gcs_to_bq.py", line 288, in execute
    encryption_configuration=self.encryption_configuration)
  File "/home/ludicxx/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1297, in run_load
    return self.run_with_configuration(configuration)
  File "/home/ludicxx/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1318, in run_with_configuration
    .execute(num_retries=self.num_retries)
  File "/home/ludicxx/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ludicxx/anaconda3/envs/airflow-tutorial/lib/python3.7/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/vg-airflow-tutorial-dev/jobs?alt=json returned "Not found: Project vg-airflow-tutorial-dev">
[2020-10-12 16:16:34,242] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=bigquery_data_load, task_id=load_data, execution_date=20201012T104625, start_date=20201012T104631, end_date=20201012T104634
[2020-10-12 16:16:41,910] {logging_mixin.py:112} INFO - [2020-10-12 16:16:41,909] {local_task_job.py:103} INFO - Task exited with return code 1
